version 2.1

jobs:
  build:
    working_directory: ~/public
    docker:
      - image: cimg/node:24.11.0
    steps:
      - checkout

      - run:
          name: Update npm
          command: npm install -g npm@latest

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json}}

      - run:
          name: Install dependencies
          command: npm cli

      - run:
          name: Fix Jest permissions
          command: chmod +x ./node_module

      - run:
          name: Run tests
          command: npm test 

      - save_cache:
          key: dependency-cache-{{ checksum "package.json"}}
          paths:
            - ./node_modules

          
      - store-artifacts:
          path: test-results.xml
          prefix: tests

      - store_artifacts:
          path: coverage
          prefix: coverage

      - store_tests_results: 
          path: test-results.xml


